global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'udp-receiver'
    static_configs:
      - targets: ['host.docker.internal:19100']
    scrape_interval: 1s
    metrics_path: /metrics
  - job_name: 'forecaster-forecasts'
    static_configs:
      - targets: ['forecaster:5000']
    scrape_interval: 15s
    metrics_path: /metrics