services:

  topology:
    build:
      context: ./services/topology
    container_name: nd-topology
    environment:
      - TOPOLOGY_PORT=8001
    ports:
      - "8001:8001"
    volumes:
      - ./base_files:/app/base_files:ro
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: nd-prometheus
    volumes:
      - ./databases/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: nd-grafana
    user: root
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - topology
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  forecaster:
    build:
      context: ..
      dockerfile: docker_setup/services/forecaster/Dockerfile
    container_name: nd-forecaster
    environment:
      - PROMETHEUS_BASE_URL=http://prometheus:9090
      - FORECAST_API_PORT=5000
      - FORECAST_MODEL_DIR=/app/models
      - FORECAST_CADENCE_SECONDS=10
      - FORECAST_MAX_CONCURRENCY=8
      - FORECAST_RETRAIN_DAYS=1
      - FORECAST_FILTER_CONFIG=/srv/app/app/forecast/metrics_filter.yaml
      - FORECAST_LOG_LEVEL=INFO
      - FORECAST_LOOKBACK_MINUTES=180
      - FORECAST_HORIZON_MINUTES=30
      - FORECAST_CLIP_Z=2.5
      #- FORECAST_BASELINE_STRATEGY=last
      #- FORECAST_BASELINE_WEIGHT=0.1
      # FORECAST_ARIMA_ORDER sets the (p,d,q) parameters for the ARIMA model: p=autoregressive terms, d=differences, q=moving average terms
      - FORECAST_ARIMA_ORDER=2,1,2
    ports:
      - "5000:5000"
    depends_on:
      - prometheus
    volumes:
      - ./forecaster_models:/app/models
    restart: unless-stopped

volumes:
  prometheus_data: {}
  grafana_data: {}
  forecaster_models: {}
